# Generated by Django 4.0.2 on 2022-02-15 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyTry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('documento', models.FileField(upload_to='uploads/')),
                ('fechadenacimiento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('usuario', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('telefono', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
                ('lugarderecidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotifyTry.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.CharField(max_length=600)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='persona',
            name='tipodocumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotifyTry.tipodocumento'),
        ),
    ]
